copy /B "train_1.txt" "train.txt"
copy /B "train.txt" + /B "train_2.txt"
copy /B "train.txt" + /B "train_3.txt"
copy /B "train.txt" + /B "train_4.txt"
copy /B "train.txt" + /B "train_5.txt"
copy /B "train.txt" + /B "train_6.txt"
copy /B "train.txt" + /B "train_7.txt"
copy /B "train.txt" + /B "train_8.txt"
copy /B "train.txt" + /B "train_9.txt"
